### ISSUE TITLE
Add versions so this could be on rails-assets

### ISSUE THREAD

**Issue by bunnymatic** [keithio/angular-mailchimp#10]
when i go here `https://rails-assets.org/components/new` and try to add your component, it reports `angular-mailchimp has no versions defined. Please create an issue in component's repository.`  

I think you need to add a release or tag (like ngDialog has done https://github.com/likeastore/ngDialog/releases).

I'd love to be able to pull this from rails assets.

cheers

**Comment by keithio** [comment]
Thanks for the recommendation. Please find it below.

https://github.com/keithio/angular-mailchimp/releases/tag/v0.0.3

**Comment by bunnymatic** [comment]
So fast.  Thanks a bunch.

![screen shot 2015-05-12 at 12 15 28 am](https://cloud.githubusercontent.com/assets/427380/7581805/1aea2f88-f83c-11e4-8868-06f3c72d94ab.png)

**Comment by bunnymatic** [comment]
Thanks for the component.  i just ripped out a pile of jQuery and templating and replaced it quickly with this angular component.  good stuff!  :rocket:
