### ISSUE TITLE
can you release latest code?

### ISSUE THREAD

**Issue by kuceram** [keithio/angular-mailchimp#13]
thx

**Comment by keithio** [comment]
Can you clarify please?

**Comment by kuceram** [comment]
What I am missing in latest release in bower is a broadcast on root scope (https://github.com/keithio/angular-mailchimp/blob/master/angular-mailchimp.js#L71). Current release doesn't have this event.

**Comment by keithio** [comment]
Fixed. Sorry for the _long_ delay.

https://github.com/keithio/angular-mailchimp/releases/tag/v0.0.4

**Comment by kuceram** [comment]
Great! :+1:
