### ISSUE TITLE
How do I use groups (checkboxes)?

### ISSUE THREAD

**Issue by ozcarstorm** [keithio/angular-mailchimp#18]
Hi! How can I use checkboxes (groups) as custom fields?
http://kb.mailchimp.com/lists/groups/add-groups-to-a-list

Is it possible? If so, how would the `ng-model=""` look like?

Thanks!

**Comment by keithio** [comment]
Looks like it's not possible using embedded forms. You'll have to use a popup.

> Group fields can be required on  pop-up signup forms, but not on hosted or  embedded signup forms. Advanced, paid users can use the  Advanced Forms option to custom-code a required group field.
