### ISSUE TITLE
Blank email address ...

### ISSUE THREAD

**Issue by tmatijev** [keithio/angular-mailchimp#7]
Hi there! I think there is an error in your form example. Instead of:

ng-model="mailchimp.email"

You must uppercase email like this:

ng-model="mailchimp.EMAIL"

Instead you are getting "Blank email address" error

**Comment by wootwoot1234** [comment]
Yeah I had to change LNAME FNAME and EMAIL in the form to capitals for it to work but it works great now.  Thanks!

**Comment by crisu83** [comment]
Same here, capitalizing EMAIL worked for me as well.

**Comment by numerized** [comment]
+1 it worked for me too :)))
